<?PHP
//config file generated by install.php
$rssgmfoldername="rssgm";   //folder where rssgm is installed relative to the DocumentRoot.
$mysitename = "Your Site Name"; //name for your site
$mainkeyword = "Your Main Keyword Phrase";  //primary site keyword
$show_google = "1"; // Show google ads ?
$adsense_pub = "pub-xxxxxxxxxxxxxxxx";  //your adsense publisher code
$adsense_channel = "";  // adsense channel
$show_chitika = "1";    // Show chitika ads ?
$chitika_pub = "xxxxxxxxxx";    //chitika publisher ID
$chitika_channel = "";  // chitika channel
$_aff = "851";  //PeakClick ID
$_subaff = "";  //PeakClick sub-affilite ID
$_numResults = "5"; //Number of Peakclick results to show
$_thumbs = "1"; //include Peakclick thumbnails
$article_type = "seed"; //type of article (none/org/seed)

$sf_account_id = "42351";
$sf_track_id = "Q4731230154";

##############

//------------------------------------//
//DON'T EDIT UNLESS A RSSGM DEVELOPER//
//------------------------------------//


$site = "http://"; 

$site .= $_SERVER["HTTP_HOST"]; 

$sitexml = $site."/";

$full = $_SERVER["REQUEST_URI"]; 

$dir = dirname($full);

$dir = str_replace("/rssgm", "", $dir);

$site .= $dir;

//--

$nr_links = 25;

$template_index = "theindex.php";

$template_pages = "pages.php";
$template_number = "3";

$template_sitemap = "thesitemap.php";

require_once("google_function.php");
require_once("chitika_function.php");

//----------------------------------//
?>
